version: '3'

services:
  db:
    image: postgres:latest
    container_name: dangobot-postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  database:
