# Generated by Django 2.0.3 on 2018-04-02 19:25

import dangobot.commands.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.TextField(max_length=2000)),
                ('response', models.TextField(blank=True, max_length=2000)),
                ('file', models.FileField(blank=True, upload_to=dangobot.commands.models.file_path)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Guild')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('guild', 'trigger')},
        ),
    ]
