# Generated by Django 2.0.7 on 2018-07-31 22:13

import dangobot.commands.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_add_original_file_name_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='file',
            field=models.FileField(blank=True, max_length=300, upload_to=dangobot.commands.models.file_path),
        ),
    ]
