#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $DATABASE_NAME;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname $DATABASE_NAME <<-EOSQL
    REVOKE CREATE ON SCHEMA public FROM public;
    REVOKE ALL ON DATABASE $DATABASE_NAME FROM public;

    CREATE ROLE dangobot_role;
    GRANT CONNECT ON DATABASE $DATABASE_NAME TO dangobot_role;
    GRANT USAGE, CREATE ON SCHEMA public TO dangobot_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dangobot_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dangobot_role;
    GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO dangobot_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO dangobot_role;

    CREATE USER $DATABASE_USER WITH PASSWORD '$DATABASE_PASSWORD';
    GRANT dangobot_role TO $DATABASE_USER;
EOSQL
