# Generated by Django 2.1.2 on 2018-11-22 21:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField()),
                ('kwargs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('scheduled_time', models.DateTimeField()),
            ],
        ),
    ]
