{{- if not .Values.bot.secrets.existingSecretName }}
{{- $botToken := .Values.bot.secrets.botToken | required ".Values.bot.secrets.botToken is required when not using an external secret." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dangobot.secretName" . }}
  labels:
    {{- include "dangobot.labels" . | nindent 4 }}
stringData:
  {{ .Values.bot.secrets.botTokenKey }}: {{ .Values.bot.secrets.botToken }}
  {{ .Values.bot.secrets.djangoSecretKey }}: {{ .Values.bot.secrets.djangoSecret }}
{{ end -}}
