# Generated by Django 2.1.8 on 2019-04-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='command_prefix',
            field=models.CharField(default='!', max_length=5),
        ),
    ]
