# Generated by Django 3.2 on 2021-04-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleForVoiceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('voice_channel_id', models.BigIntegerField()),
                ('role_id', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('voice_channel_id', 'role_id')},
            },
        ),
    ]
