# Generated by Django 2.0.3 on 2018-03-13 14:12

from django.db import migrations, models
import django.db.models.deletion
import plugins.responder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.TextField(max_length=2000)),
                ('response', models.TextField(blank=True, max_length=2000)),
                ('file', models.FileField(blank=True, upload_to=plugins.responder.models.file_path)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Server')),
            ],
        ),
    ]
