# Generated by Django 2.0.3 on 2018-03-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
        ('responder', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('server', 'trigger')},
        ),
    ]
