name: Main

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Setup Pipenv
        run:
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        run:
          pipenv sync --system --dev

      - name: Run flake8 linting
        run: flake8

      - name: Run pylint linting
        run: pylint dangobot
