name: Main

on: [push, pull_request]

env:
  # CI only secrets in order to allow django to boot, not used anywhere else
  SECRET_KEY: '1234567890abcd'
  BOT_TOKEN: '1234567890abcd'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Setup Pipenv
        run:
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        run:
          pipenv install --system --deploy --dev

      - name: Install the settings file
        run:
          cp settings.py.docker settings.py

      - name: Run flake8 linting
        run: flake8

      - name: Run pylint linting
        run: pylint dangobot
